# Generated by Django 4.1.1 on 2022-11-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default=0, upload_to='uploads/photos'),
            preserve_default=False,
        ),
    ]
